export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const ADD_PRODUCT= 'ADD_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const UPDATE_PRODUCT_IN_PRODUCTS = 'UPDATE_PRODUCT_IN_PRODUCTS';